language: node_js
node_js:
- '12.4.0'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: develop
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master